# general args
resume: /path/to/pth.tar
pre_trained: False
test: valid

# Dataset
dataset: KITTI
data_root: /path/to/KITTI_RAW
num_points: 32768
val_samples: -1

# miscalleneous
workers: 4

# Test args
save_image: False
