# general args
test: False
ckpt_dir: /path/to/save/ckpt
resume: False
pre_trained: False

# Dataset
dataset: KITTI
data_root: /path/to/KITTI_RAW
num_points: 32768
train_samples: -1
val_samples: -1

# for model
arch: ABCD
last_relu: False

use_leaky: True
bcn_use_bias: True
bcn_use_norm: True

DEVICE: cuda

dim: 3
batch_size: 1
scales_filter_map: [[8., 1],
                    [4., 1],
                    [2., 1],
                    [1., 1],
                    [0.5, 1],
                    ]
pc_feat_channel: 32
resnet: resnet34

# miscalleneous
workers: 4

# Train args
weight_decay: 0.0
lr: 0.0001
epochs: 30
iter_iterval: 10000

